<?php
if (!defined("PJ_HOST")) define("PJ_HOST", "mysqlsvr39.world4you.com");
if (!defined("PJ_USER")) define("PJ_USER", "sql4416661");
if (!defined("PJ_PASS")) define("PJ_PASS", "igs24jg");
if (!defined("PJ_DB")) define("PJ_DB", "4416661db3");
if (!defined("PJ_PREFIX")) define("PJ_PREFIX", "");
if (!defined("PJ_INSTALL_FOLDER")) define("PJ_INSTALL_FOLDER", "/schedule/");
if (!defined("PJ_INSTALL_PATH")) define("PJ_INSTALL_PATH", "/home/.sites/142/site4416661/web/schedule/");
if (!defined("PJ_INSTALL_URL")) define("PJ_INSTALL_URL", "http://www.hausfabrik.at/schedule/");
if (!defined("PJ_SALT")) define("PJ_SALT", "YHRKT8LS");
if (!defined("PJ_INSTALLATION")) define("PJ_INSTALLATION", "MTIyMjI1MjEwMjQ2NDM0NzgxMDU1MDg4NjgzNTgxNTA4NzM0MzQ1ODYzNDg0OTgyMDMwNTk0MDgxMzkwNTAxODk3NzYwMjUxNjIxNTQxMTM5MTk0ODU5MjczMTM3NTM2ODcwMSA2MjEzMTE0MDE3NjY4MjM4NTMxOTIxNTgwODU3MzcyMzI4MjE5NjM0NzYwNzg5NDA4MDk1NzEzOTI2NDQ1MTM2MjI3ODgyMjE3NDE1MjE2ODAxMTYyODEzNjM0NTk5MTc3MTQgNTkyNjIyMDY3MTI3MjUyODAyNjY2OTM0NzE5ODIyMjAyMjc1ODg0MDU1MjI3NTQwOTQ1Mjg3MjAyNjk0OTQzNjQzNjk1NjEyNzk3MTk5MTIzNjIyNjIzMzQzMTI1MTU0ODcwIDEzMzQ4MDkyMzY1NTE3NDk3ODY0MzA2NDIwMzgxMjc5MjE5MjQyMzY5NDk1MTAyMjYwNDkxMTE0NzczNjgxNjY5NDA2OTMwNzE5MzUxMjQ5NzQ1NTMyOTYxMDMxMTI2MjM5NDkgMjQxNTk3MDY4NDk1Nzg4MTc4MzEwNzA4NDI0MTI2NjM4MzI3OTIyMjY3OTc0NzgyNDgxNDQ0OTY0MTg5ODMyNjM5MTA3MzIyMjcyNjg3NzcxMTU0OTI1ODQ3MzM3OTcyNDAzIDE1MzA3MDcwNjUyOTM3Njk3MzQ0NTE2ODE0NDEyMTI3MjM4Njk3NTQ5Nzg3OTQ1ODY1NTAxNjA1MTY3MDI4NTYwNTk5MjU4NTc2NjI3MjQxOTQ4ODU5MjA4MDE2NTY5NDkwMQ==");
?>