<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StripePayment\Controller\Base;

use StripePayment\StripePayment;
use StripePayment\Classes\StripePaymentLog;
use Thelia\Controller\Admin\BaseAdminController;
use Thelia\Form\Exception\FormValidationException;
use Thelia\Core\HttpFoundation\Response;
use Thelia\Core\Security\Resource\AdminResources;
use Thelia\Core\Security\AccessManager;
use StripePayment\Model\Config\StripePaymentConfigValue;

/**
 * Class StripePaymentConfigController
 * @package StripePayment\Controller\Base
 * @author TheliaStudio
 */
class StripePaymentConfigController extends BaseAdminController
{   

    const MAX_TRACE_SIZE_IN_BYTES = 40000;

    public function defaultAction()
    {
        if (null !== $response = $this->checkAuth([AdminResources::MODULE], ["stripepayment"], AccessManager::VIEW)) {
            return $response;
        }

        $logFilePath = StripePaymentLog::getLogFilePath();

        $traces = @file_get_contents($logFilePath);

        if (false === $traces) {
            $traces = $this->getTranslator()->trans("The log file doesn't exists yet.", [], StripePayment::MESSAGE_DOMAIN);
        } elseif (empty($traces)) {
            $traces = $this->getTranslator()->trans("The log file is empty.", [], StripePayment::MESSAGE_DOMAIN);
        } else {
            // Limiter la taille des traces à 1MO
            if (strlen($traces) > self::MAX_TRACE_SIZE_IN_BYTES) {
                $traces = substr($traces, strlen($traces) - self::MAX_TRACE_SIZE_IN_BYTES);
                // Cut a first line break;
                if (false !== $lineBreakPos = strpos($traces, "\n")) {
                    $traces = substr($traces, $lineBreakPos+1);
                }

                $traces = $this->getTranslator()->trans(
                    "(Previous log is in %file file.)\n",
                    [ '%file' => sprintf("log".DS."%s.log", StripePayment::MESSAGE_DOMAIN) ],
                    StripePayment::MESSAGE_DOMAIN
                ) . $traces;
            }
        }

        $vars = ['log_messages' => nl2br($traces)  ];

        return $this->render("stripepayment-configuration", $vars);
    }

    public function saveAction()
    {
        if (null !== $response = $this->checkAuth([AdminResources::MODULE], ["stripepayment"], AccessManager::UPDATE)) {
            return $response;
        }

        $baseForm = $this->createForm("stripepayment.configuration");

        $errorMessage = null;

        try {
            $form = $this->validateForm($baseForm);
            $data = $form->getData();

            StripePayment::setConfigValue(StripePaymentConfigValue::ENABLED, is_bool($data["enabled"]) ? (int) ($data["enabled"]) : $data["enabled"]);
            StripePayment::setConfigValue(StripePaymentConfigValue::SECRET_KEY, is_bool($data["secret_key"]) ? (int) ($data["secret_key"]) : $data["secret_key"]);
            StripePayment::setConfigValue(StripePaymentConfigValue::PUBLISHABLE_KEY, is_bool($data["publishable_key"]) ? (int) ($data["publishable_key"]) : $data["publishable_key"]);
        } catch (FormValidationException $ex) {
            // Invalid data entered
            $errorMessage = $this->createStandardFormValidationErrorMessage($ex);
        } catch (\Exception $ex) {
            // Any other error
            $errorMessage = $this->getTranslator()->trans('Sorry, an error occurred: %err', ['%err' => $ex->getMessage()], [], StripePayment::MESSAGE_DOMAIN);
        }

        if (null !== $errorMessage) {
            // Mark the form as with error
            $baseForm->setErrorMessage($errorMessage);

            // Send the form and the error to the parser
            $this->getParserContext()
                ->addForm($baseForm)
                ->setGeneralError($errorMessage)
            ;
        } else {
            $this->getParserContext()
                ->set("success", true)
            ;
        }

        return $this->defaultAction();
    }

    public function downloadLog()
    {
        if (null !== $response = $this->checkAuth(AdminResources::MODULE, 'atos', AccessManager::UPDATE)) {
            return $response;
        }

        $logFilePath = StripePaymentLog::getLogFilePath();

        return Response::create(
            @file_get_contents($logFilePath),
            200,
            array(
                'Content-type' => "text/plain",
                'Content-Disposition' => sprintf('Attachment;filename=log-stripe.txt')
            )
        );
    }
}
